// src/pages/about.vue
<script setup>
import { useStore } from '@/store';

const store = useStore('about');
const increment = () => store.increment();
</script>
<template>
  <q-chip icon="home">
    <router-link to="/">
      Home
    </router-link>
  </q-chip>
  <div>
    <q-btn
      class="q-ma-sm"
      @click="increment"
    >
      {{ store.count }}
    </q-btn>
  </div>
</template>

// src/pages/About.tsx
import { observer } from 'mobx-react-lite';
import { useNavigate } from 'react-router-dom';
import { useStore } from '@/store';

const About = observer(() => {
  const store = useStore('about');
  const navigate = useNavigate();

  return <div>
    <button onClick={() => navigate('/')}>home</button>
    <button onClick={() => store.increment()}>{store.count}</button>
  </div>;
});

export default About;
