// src/pages/home.vue
<script lang="ts">
import { useStore } from '@/store';
import { PrefetchContext } from '@/main';

export default {
  name: 'HomePage',
  prefetch(ctx: PrefetchContext) {
    return ctx.store.home.fetchName();
  },
  setup() {
    const store = useStore('home');
    const hello = `hello ${store.name.value}`;

    return {
      hello,
    };
  },
};

</script>
<template>
  <div>
    <router-link to="/about">
      About
    </router-link>
    <div class="scoped">
      {{ hello }}
    </div>
  </div>
</template>
<style lang="scss" scoped>
.scoped {
  color: blue;
}
</style>

// src/pages/Home.tsx
import { observer } from 'mobx-react-lite';
import { useStore } from '@/store';
import { PrefetchContext } from '@/App';
import { useNavigate } from 'react-router-dom';

export const prefetch = (ctx: PrefetchContext) => ctx.store.home.fetchName();

const Home = observer(() => {
  const store = useStore('home');
  const hello = `hello ${store.name}`;
  const navigate = useNavigate();

  return <div>
    <button onClick={() => navigate('/about')}>about</button>
    <div>{hello}</div>
  </div>;
});

export default Home;
